### ISSUE TITLE
Want to stop Brinks connection problems on my BHS-3000C.

### ISSUE THREAD

**Issue by axux** [flarn2006/BHSTools#1]
I would like to stop Brinks connection problems on my BHS-3000C. I plugged the RS-485 adapter into the required pins on the panel and saw packet exchange in the terminal but nothing on the virtual screen on the web interface. Are there any steps that I'm missing?

**Comment by flarn2006** [comment]
I've actually only tested it on a BHS-4000, so I can't say for sure whether or not it will work on a 3000. It should though, because it uses the same programmer.

Try clicking the Esc button on the interface when you're connected; sometimes the screen doesn't activate automatically.

**Comment by axux** [comment]
@flarn2006 Thanks so much for replying, I've had a Google search alert for info on programming these panels for the longest time and it's great that there's being some work done. I'll try the escape solution and give an update on the results. The "s3121.py" file is the file that I've been using in my tests, is this right? Thanks so much!

**Comment by flarn2006** [comment]
Yes, that's correct. I assume you're specifying the serial port on the
command line? I figure you got that part right because you got the web
interface open.

What data are you seeing in the console? Were there a lot of hex digits?
Specifically a lot of lines beginning with "DA 07" and/or "DB 07"? If so,
that's a good sign.

**Comment by axux** [comment]
@flarn2006 Yes, I did specify the port and got the hex output, it was just the web interface not updating. I'll test it when I can.

**Comment by flarn2006** [comment]
OK let me know how it goes. If Esc doesn't do anything, try clicking the
number buttons and tell me if asterisks appear on the screen.

**Comment by flarn2006** [comment]
Just got my BHS-3000 in the mail today and I can confirm it is compatible.

**Comment by axux** [comment]
@flarn2006 Can you link to the adapter that you’re using?

**Comment by axux** [comment]
@flarn2006 Sorry to bother you again but just out of curiosity, where do you source your panels? I've been looking for one for a while and it relatively challenging to find any answers when it comes to proprietary alarms.

**Comment by flarn2006** [comment]
I've just found them on Ebay.

**Comment by axux** [comment]
@flarn2006 Thanks for your help, I ended up just getting frustrated and removing the speaker from the keypad.

**Comment by flarn2006** [comment]
The tool wasn't working even when pressing Esc? You know I mean the button
on the screen, not the Esc key on the keyboard, right?

**Comment by axux** [comment]
I was pressing the button on the keyboard, whoops. I no longer have a reason to try to program it but I have been considering buying another panel as a test. Thanks for all your help.

**Comment by tooltimmy** [comment]
Thank you for the the excellent creation, I have successfully connected to and made changes to my panel but I want to download the entire database and the download proses is randomly stopping. Can you give me some ideas on what may be happening?

**Comment by flarn2006** [comment]
That's a known issue; I've been meaning to do something about it.

**Comment by flarn2006** [comment]
@tooltimmy: Is this a BHS-3000 or BHS-4000?

**Comment by voyager1498** [comment]
Everything was working fine but my computer needed to reboot for a system reboot and now the web interface does not seem to update any ideas what the problem might be?
